name: Nuget Publish
 
on:
  push:
    branches: [ chance_dev ]
  pull_request:
    branches: [ chance_dev ]
 
jobs:
  build: 
    runs-on: windows-latest
 
    steps:
    - name: CheckOut
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Install nuget 
      uses: nuget/setup-nuget@v1
      with:        
        nuget-version: '5.x'
      
    - name: Add to github package
      run: |
        nuget sources add -name github -Source https://nuget.pkg.github.com/ORGANIZATION_NAME/index.json -Username ORGANIZATION_NAME -Password ${{ secrets.GITHUBACCESSTOKEN }}    
        
    - name: Publish package to nuget
      run: |
        nuget push .\Output\bin\Release\*.nupkg -Source github -SkipDuplicate
        nuget push .\Output\bin\Release\*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NUGETAPIKEY }} -NoSymbols