name: WakaTime

on:
  push:
    branches:
      - chance_dev
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: <chancezheng/chancezheng>
          SHOW_TITLE: true
          SHOW_EDITORS: true
          SHOW_OS: true
