name: WakaTime Readme

on:
  push:
    branches:
      - chance_dev
  schedule:
    - cron: '0 19 * * *'

jobs:
  update-readme:
    runs-on: windows-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
