name: WakaTime

on:
  push:
    branches:
      - chance_dev
  schedule:
    - cron: '0 1 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: chancezheng/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WATATIME_TOKEN: ${{ secrets.WATATIME_TOKEN }}
          SHOW_EDITORS: true
          SHOW_OS: true
